# 待检测的 AprilTag 定义
#
# - 所有尺寸单位为 米
# - 'size' 指黑色与白色矩形共享边的长度
#
standalone_tags:
  [
    {id: 1, size: 0.06, name: 'tag_1'},
    {id: 2, size: 0.06, name: 'tag_2'},
    {id: 3, size: 0.06, name: 'tag_3'},
    {id: 4, size: 0.06, name: 'tag_4'},
  ]

tag_bundles:
  [
  ]
